name: test, build and deploy
on:
  - push
jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test