name: test, build and deploy
on:
  - push
jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test

  build_and_push:
    runs-on: ubuntu-latest
    needs:
      - unit_tests
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm i
      - name: webpack build
        run: npm run build
      - name: docker build
        run: docker build -t golosovsa/skypro-fd-cw4:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: docker push
        run: docker push golosovsa/skypro-fd-cw4:$GITHUB_REF_NAME-$GITHUB_RUN_ID
